package com.galosanchez.view;

import com.galosanchez.controller.LoanController;
import com.galosanchez.domain.Loan;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 * Esta clase permite ver y editar un prestamo
 * @author Galo Sánchez
 */
public class DialogEditLoan extends javax.swing.JDialog {

    private int xMouse, yMouse;
    private final JFrame jFrameParent;
    private final Loan loan;
    private char state;

    public DialogEditLoan(JFrame parent, boolean modal, Loan loan) {
        super(parent, modal);
        this.jFrameParent = parent;
        this.loan =loan;
        initComponents();

        /* Fondo de JDialog tranparente */
        this.setBackground(new Color(0, 0, 0, 0));
        bg.setBackground(new Color(0, 0, 0, 0));
        /* Cargar datos del prestamo*/
        loadDataLoan();
        /* Hacer que el jLabel del boton Crear sea focusable */
        jLabelButtonCreate.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDevuelto = new javax.swing.ButtonGroup();
        jPanelContent = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelClose = new javax.swing.JPanel();
        jImgClose = new javax.swing.JLabel();
        jPanelDivide = new javax.swing.JPanel();
        jPanelForm = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldPrestado = new javax.swing.JTextField();
        jPanelFocusName = new javax.swing.JPanel();
        jLabelLastName = new javax.swing.JLabel();
        jTextFieldDevuelto = new javax.swing.JTextField();
        jPanelFocusLastName = new javax.swing.JPanel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldBook = new javax.swing.JTextField();
        jPanelFocusEmail = new javax.swing.JPanel();
        jLabelCI = new javax.swing.JLabel();
        jTextFieldStudent = new javax.swing.JTextField();
        jPanelFocusCI = new javax.swing.JPanel();
        jLabelPhone = new javax.swing.JLabel();
        jPanelButtonCreate = new javax.swing.JPanel();
        jLabelButtonCreate = new javax.swing.JLabel();
        jLabelPhone1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPaneDetail = new javax.swing.JEditorPane();
        jRadioButtonYes = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLeft.setBackground(new java.awt.Color(123, 31, 162));

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 532));

        jPanelTop.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelTopMouseDragged(evt);
            }
        });
        jPanelTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTopMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 20));

        jLabelTitle.setFont(new java.awt.Font("Hind Siliguri SemiBold", 0, 20)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(123, 31, 162));
        jLabelTitle.setText("Detalles del préstamo");
        jPanelContent.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 0, -1, 65));

        jPanelClose.setBackground(new java.awt.Color(255, 255, 255));

        jImgClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImgClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/ic_close_dialog.png"))); // NOI18N
        jImgClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImgCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jImgCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jImgCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCloseLayout = new javax.swing.GroupLayout(jPanelClose);
        jPanelClose.setLayout(jPanelCloseLayout);
        jPanelCloseLayout.setHorizontalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImgClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCloseLayout.setVerticalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImgClose, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 14, 40, 40));

        jPanelDivide.setBackground(new java.awt.Color(224, 224, 224));

        javax.swing.GroupLayout jPanelDivideLayout = new javax.swing.GroupLayout(jPanelDivide);
        jPanelDivide.setLayout(jPanelDivideLayout);
        jPanelDivideLayout.setHorizontalGroup(
            jPanelDivideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanelDivideLayout.setVerticalGroup(
            jPanelDivideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 65, 460, 1));

        jPanelForm.setBackground(new java.awt.Color(255, 255, 255));
        jPanelForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelName.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(158, 158, 158));
        jLabelName.setText("Prestado");
        jPanelForm.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 16));

        jTextFieldPrestado.setEditable(false);
        jTextFieldPrestado.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPrestado.setFont(new java.awt.Font("Hind Siliguri", 0, 16)); // NOI18N
        jTextFieldPrestado.setForeground(new java.awt.Color(33, 33, 33));
        jTextFieldPrestado.setBorder(null);
        jTextFieldPrestado.setDisabledTextColor(new java.awt.Color(33, 33, 33));
        jPanelForm.add(jTextFieldPrestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, 200, 20));

        jPanelFocusName.setBackground(new java.awt.Color(158, 158, 158));

        javax.swing.GroupLayout jPanelFocusNameLayout = new javax.swing.GroupLayout(jPanelFocusName);
        jPanelFocusName.setLayout(jPanelFocusNameLayout);
        jPanelFocusNameLayout.setHorizontalGroup(
            jPanelFocusNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanelFocusNameLayout.setVerticalGroup(
            jPanelFocusNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanelForm.add(jPanelFocusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 200, 1));

        jLabelLastName.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelLastName.setForeground(new java.awt.Color(158, 158, 158));
        jLabelLastName.setText("Devolución");
        jPanelForm.add(jLabelLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 16));

        jTextFieldDevuelto.setEditable(false);
        jTextFieldDevuelto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDevuelto.setFont(new java.awt.Font("Hind Siliguri", 0, 16)); // NOI18N
        jTextFieldDevuelto.setForeground(new java.awt.Color(33, 33, 33));
        jTextFieldDevuelto.setBorder(null);
        jTextFieldDevuelto.setDisabledTextColor(new java.awt.Color(33, 33, 33));
        jPanelForm.add(jTextFieldDevuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 22, 200, 20));

        jPanelFocusLastName.setBackground(new java.awt.Color(158, 158, 158));

        javax.swing.GroupLayout jPanelFocusLastNameLayout = new javax.swing.GroupLayout(jPanelFocusLastName);
        jPanelFocusLastName.setLayout(jPanelFocusLastNameLayout);
        jPanelFocusLastNameLayout.setHorizontalGroup(
            jPanelFocusLastNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanelFocusLastNameLayout.setVerticalGroup(
            jPanelFocusLastNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanelForm.add(jPanelFocusLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 46, 200, 1));

        jLabelEmail.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(158, 158, 158));
        jLabelEmail.setText("Libro");
        jPanelForm.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, -1, 16));

        jTextFieldBook.setEditable(false);
        jTextFieldBook.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldBook.setFont(new java.awt.Font("Hind Siliguri", 0, 16)); // NOI18N
        jTextFieldBook.setForeground(new java.awt.Color(33, 33, 33));
        jTextFieldBook.setBorder(null);
        jPanelForm.add(jTextFieldBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 420, 20));

        jPanelFocusEmail.setBackground(new java.awt.Color(158, 158, 158));

        javax.swing.GroupLayout jPanelFocusEmailLayout = new javax.swing.GroupLayout(jPanelFocusEmail);
        jPanelFocusEmail.setLayout(jPanelFocusEmailLayout);
        jPanelFocusEmailLayout.setHorizontalGroup(
            jPanelFocusEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanelFocusEmailLayout.setVerticalGroup(
            jPanelFocusEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanelForm.add(jPanelFocusEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 113, 420, 1));

        jLabelCI.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelCI.setForeground(new java.awt.Color(158, 158, 158));
        jLabelCI.setText("Estudiante");
        jPanelForm.add(jLabelCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 136, -1, 16));

        jTextFieldStudent.setEditable(false);
        jTextFieldStudent.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldStudent.setFont(new java.awt.Font("Hind Siliguri", 0, 16)); // NOI18N
        jTextFieldStudent.setForeground(new java.awt.Color(33, 33, 33));
        jTextFieldStudent.setBorder(null);
        jPanelForm.add(jTextFieldStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 156, 420, 20));

        jPanelFocusCI.setBackground(new java.awt.Color(158, 158, 158));

        javax.swing.GroupLayout jPanelFocusCILayout = new javax.swing.GroupLayout(jPanelFocusCI);
        jPanelFocusCI.setLayout(jPanelFocusCILayout);
        jPanelFocusCILayout.setHorizontalGroup(
            jPanelFocusCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanelFocusCILayout.setVerticalGroup(
            jPanelFocusCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanelForm.add(jPanelFocusCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 420, 1));

        jLabelPhone.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelPhone.setForeground(new java.awt.Color(158, 158, 158));
        jLabelPhone.setText("Detalles");
        jPanelForm.add(jLabelPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 203, -1, 16));

        jPanelButtonCreate.setBackground(new java.awt.Color(156, 39, 176));

        jLabelButtonCreate.setFont(new java.awt.Font("Hind Siliguri Medium", 0, 14)); // NOI18N
        jLabelButtonCreate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelButtonCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonCreate.setText("Guardar");
        jLabelButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonCreateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonCreateLayout = new javax.swing.GroupLayout(jPanelButtonCreate);
        jPanelButtonCreate.setLayout(jPanelButtonCreateLayout);
        jPanelButtonCreateLayout.setHorizontalGroup(
            jPanelButtonCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButtonCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );
        jPanelButtonCreateLayout.setVerticalGroup(
            jPanelButtonCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButtonCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanelForm.add(jPanelButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 394, 78, 32));

        jLabelPhone1.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelPhone1.setForeground(new java.awt.Color(158, 158, 158));
        jLabelPhone1.setText("Devuelto");
        jPanelForm.add(jLabelPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 296, -1, 16));

        jScrollPane2.setFont(new Font("Hind Siliguri", Font.PLAIN, 16));

        jEditorPaneDetail.setFont(new Font("Hind Siliguri", Font.PLAIN, 16));
        jEditorPaneDetail.setForeground(new java.awt.Color(33, 33, 33));
        jEditorPaneDetail.setMaximumSize(new java.awt.Dimension(418, 50));
        jEditorPaneDetail.setMinimumSize(new java.awt.Dimension(418, 50));
        jEditorPaneDetail.setPreferredSize(new java.awt.Dimension(418, 50));
        jScrollPane2.setViewportView(jEditorPaneDetail);

        jPanelForm.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 224, -1, -1));

        jRadioButtonYes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupDevuelto.add(jRadioButtonYes);
        jRadioButtonYes.setFont(new Font("Hind Siliguri", Font.PLAIN, 16));
        jRadioButtonYes.setForeground(new java.awt.Color(33, 33, 33));
        jRadioButtonYes.setText("Si");
        jPanelForm.add(jRadioButtonYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 318, 50, 25));

        jRadioButtonNo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupDevuelto.add(jRadioButtonNo);
        jRadioButtonNo.setFont(new Font("Hind Siliguri", Font.PLAIN, 16));
        jRadioButtonNo.setForeground(new java.awt.Color(33, 33, 33));
        jRadioButtonNo.setText("No");
        jPanelForm.add(jRadioButtonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 318, 50, 25));

        jPanelContent.add(jPanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 86, 420, 426));

        getContentPane().add(jPanelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 475, 532));

        bg.setPreferredSize(new java.awt.Dimension(505, 406));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/bg_edit_loan.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(505, 406));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(505, 406));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 505, 562));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Eventos que permiten arrastrar la ventana desde la barra superior
     */
    private void jPanelTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelTopMousePressed

    private void jPanelTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelTopMouseDragged

    /**
     * Eventos que perminen a los botones cerrar y minimizar ventana
     */
    private void jImgCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImgCloseMouseEntered
        jPanelClose.setBackground(new java.awt.Color(245, 245, 245));
    }//GEN-LAST:event_jImgCloseMouseEntered

    private void jImgCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImgCloseMouseExited
        jPanelClose.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jImgCloseMouseExited

    private void jImgCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImgCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jImgCloseMouseClicked

    /**
     * Metodo que permite cambiar de color de JPanel que esta debajo de un
     * TextFied para mejorar la experiencia de usurio. Dependiendo del tipo que
     * ingrese "Gained" : color de foco, o "Lost": color normal Ingresa el
     * JPanel al que se aplica el cambio
     *
     * @param tipo
     * @param panelSeparator
     */
    public void chanceColorFocusSeparator(String tipo, JPanel panelSeparator) {
        if (tipo.equals("Gained")) {
            panelSeparator.setBackground(new java.awt.Color(123, 31, 162));
            return;
        }
        if (tipo.equals("Lost")) {
            panelSeparator.setBackground(new java.awt.Color(158, 158, 158));
        }
    }

    /**
     * Eventos de boton "Crear usuario". Mejorar apariencial al entrar con el
     * mouse
     */
    private void jLabelButtonCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCreateMouseEntered
        if(state=='D')return;
        jPanelButtonCreate.setBackground(new java.awt.Color(123, 31, 162));
    }//GEN-LAST:event_jLabelButtonCreateMouseEntered

    private void jLabelButtonCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCreateMouseExited
        if(state=='D')return;
        jPanelButtonCreate.setBackground(new java.awt.Color(156, 39, 176));
    }//GEN-LAST:event_jLabelButtonCreateMouseExited

    /**
     * Evento click del boton "Crear usuario".
     */
    private void jLabelButtonCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCreateMouseClicked
        if(state=='D')return;
        
        if(jEditorPaneDetail.getText().equals(loan.getDetail()) && jRadioButtonNo.isSelected())
            return;
        
        Loan updateLoan = new Loan();
        updateLoan.setId_loan(loan.getId_loan());
        updateLoan.setDetail(jEditorPaneDetail.getText());
        if(jRadioButtonYes.isSelected()){
            updateLoan.setState('D');
        }else{
            updateLoan.setState('L');
        }
        /* Enviar datos a la base de datos */
        try {
            // Se comprueba que los datos se ingresen correctamente a la base
            if (LoanController.actualizarPrestamo(updateLoan) > 0) {
                openDialogAlert("successful", " ","Actualizado correctamente","");
                // cerrar ventana
                this.dispose();
            // Sino lanzar un mensaje de alerta
            } else {
                openDialogAlert("warning", "Error al crear","");
            }
        } catch (Exception e) {
            // Errores con la base de datos
            if (e.getLocalizedMessage().equals("3011")) {
                openDialogAlert("danger", "No se puede establecer conexión con el","servidor");
            } else {
                openDialogAlert("danger", "Error al momento de consultar al servidor","");
            }
        }

    }//GEN-LAST:event_jLabelButtonCreateMouseClicked

    /**
     * Método que crea un alert para lanzar un mensaje positivo
     * @param tipo
     * @param message1
     * @param message2 
     */
    private void openDialogAlert(String tipo, String message1, String message2) {
        DialogAlert dialogAlert = new DialogAlert(jFrameParent, true, tipo, message1, message2);
        dialogAlert.setVisible(true);
    }
    
    /**
     * Método que crea un alert para lanzar un mensaje
     * @param tipo
     * @param title
     * @param message1
     * @param message2 
     */
    private void openDialogAlert(String tipo,String title, String message1, String message2) {
        DialogAlert dialogAlert = new DialogAlert(jFrameParent, true, tipo,title, message1, message2);
        dialogAlert.setVisible(true);
    }

    /**
     * Método que carga los datos del prestamo en los elementos de la interfáz
     */
    private void loadDataLoan() {
        jTextFieldPrestado.setText(loan.getDate_prestamo().toString());
        jTextFieldDevuelto.setText(loan.getDate_devolucion().toString());
        jTextFieldBook.setText(loan.getCopyBook().getCode()+" - "+loan.getCopyBook().getBook().getTitle());
        jTextFieldStudent.setText(loan.getStudent().getName()+" "+ loan.getStudent().getLastName()+" - "+loan.getStudent().getCedula());
        jEditorPaneDetail.setText(loan.getDetail());
        state = loan.getState();
        if (state == 'L'){
            jRadioButtonNo.setSelected(true);
            
        }else{
            jRadioButtonYes.setSelected(true);
            jEditorPaneDetail.setEditable(false);
            jRadioButtonYes.setEnabled(false);
            jRadioButtonNo.setEnabled(false);
            jPanelButtonCreate.setBackground(new java.awt.Color(168, 123, 176));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.ButtonGroup buttonGroupDevuelto;
    private javax.swing.JEditorPane jEditorPaneDetail;
    private javax.swing.JLabel jImgClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelButtonCreate;
    private javax.swing.JLabel jLabelCI;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPhone1;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelButtonCreate;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelDivide;
    private javax.swing.JPanel jPanelFocusCI;
    private javax.swing.JPanel jPanelFocusEmail;
    private javax.swing.JPanel jPanelFocusLastName;
    private javax.swing.JPanel jPanelFocusName;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonYes;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldBook;
    private javax.swing.JTextField jTextFieldDevuelto;
    private javax.swing.JTextField jTextFieldPrestado;
    private javax.swing.JTextField jTextFieldStudent;
    // End of variables declaration//GEN-END:variables

    

}
