package com.galosanchez.view;

import com.galosanchez.controller.AuthorController;
import com.galosanchez.domain.Author;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 * Esta clase permite crear un nuevo Autor
 * @author Galo Sánchez
 */
public class DialogNewAuthor extends javax.swing.JDialog {

    private int xMouse, yMouse;
    private final JFrame jFrameParent;

    public DialogNewAuthor(JFrame parent, boolean modal) {
        super(parent, modal);
        this.jFrameParent = parent;
        initComponents();

        /* Fondo de JDialog tranparente */
        this.setBackground(new Color(0, 0, 0, 0));
        bg.setBackground(new Color(0, 0, 0, 0));
        /* Hacer que el jLabel del boton Crear sea focusable */
        jLabelButtonCreate.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContent = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelClose = new javax.swing.JPanel();
        jImgClose = new javax.swing.JLabel();
        jPanelDivide = new javax.swing.JPanel();
        jPanelForm = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jPanelFocusName = new javax.swing.JPanel();
        jLabelErrorName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jPanelFocusLastName = new javax.swing.JPanel();
        jLabelErrorLastName = new javax.swing.JLabel();
        jPanelButtonCreate = new javax.swing.JPanel();
        jLabelButtonCreate = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(505, 276));
        setMinimumSize(new java.awt.Dimension(505, 276));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLeft.setBackground(new java.awt.Color(123, 31, 162));

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 246));

        jPanelTop.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelTopMouseDragged(evt);
            }
        });
        jPanelTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTopMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 20));

        jLabelTitle.setFont(new java.awt.Font("Hind Siliguri SemiBold", 0, 20)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(123, 31, 162));
        jLabelTitle.setText("Nuevo autor");
        jPanelContent.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 0, -1, 65));

        jPanelClose.setBackground(new java.awt.Color(255, 255, 255));

        jImgClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImgClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/ic_close_dialog.png"))); // NOI18N
        jImgClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImgCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jImgCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jImgCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCloseLayout = new javax.swing.GroupLayout(jPanelClose);
        jPanelClose.setLayout(jPanelCloseLayout);
        jPanelCloseLayout.setHorizontalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImgClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCloseLayout.setVerticalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImgClose, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 14, 40, 40));

        jPanelDivide.setBackground(new java.awt.Color(224, 224, 224));

        javax.swing.GroupLayout jPanelDivideLayout = new javax.swing.GroupLayout(jPanelDivide);
        jPanelDivide.setLayout(jPanelDivideLayout);
        jPanelDivideLayout.setHorizontalGroup(
            jPanelDivideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanelDivideLayout.setVerticalGroup(
            jPanelDivideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanelContent.add(jPanelDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 65, 460, 1));

        jPanelForm.setBackground(new java.awt.Color(255, 255, 255));
        jPanelForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelName.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(158, 158, 158));
        jLabelName.setText("Nombres");
        jPanelForm.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 16));

        jTextFieldName.setFont(new java.awt.Font("Hind Siliguri", 0, 16)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(33, 33, 33));
        jTextFieldName.setBorder(null);
        jTextFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNameFocusLost(evt);
            }
        });
        jPanelForm.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, 200, 20));

        jPanelFocusName.setBackground(new java.awt.Color(158, 158, 158));

        javax.swing.GroupLayout jPanelFocusNameLayout = new javax.swing.GroupLayout(jPanelFocusName);
        jPanelFocusName.setLayout(jPanelFocusNameLayout);
        jPanelFocusNameLayout.setHorizontalGroup(
            jPanelFocusNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanelFocusNameLayout.setVerticalGroup(
            jPanelFocusNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanelForm.add(jPanelFocusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 200, 1));

        jLabelErrorName.setFont(new java.awt.Font("Hind Siliguri", 0, 12)); // NOI18N
        jLabelErrorName.setForeground(new java.awt.Color(205, 92, 92));
        jPanelForm.add(jLabelErrorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 200, 14));

        jLabelLastName.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelLastName.setForeground(new java.awt.Color(158, 158, 158));
        jLabelLastName.setText("Apellidos");
        jPanelForm.add(jLabelLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 16));

        jTextFieldLastName.setFont(new java.awt.Font("Hind Siliguri", 0, 16)); // NOI18N
        jTextFieldLastName.setForeground(new java.awt.Color(33, 33, 33));
        jTextFieldLastName.setBorder(null);
        jTextFieldLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLastNameFocusLost(evt);
            }
        });
        jPanelForm.add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 22, 200, 20));

        jPanelFocusLastName.setBackground(new java.awt.Color(158, 158, 158));

        javax.swing.GroupLayout jPanelFocusLastNameLayout = new javax.swing.GroupLayout(jPanelFocusLastName);
        jPanelFocusLastName.setLayout(jPanelFocusLastNameLayout);
        jPanelFocusLastNameLayout.setHorizontalGroup(
            jPanelFocusLastNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanelFocusLastNameLayout.setVerticalGroup(
            jPanelFocusLastNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanelForm.add(jPanelFocusLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 46, 200, 1));

        jLabelErrorLastName.setFont(new java.awt.Font("Hind Siliguri", 0, 12)); // NOI18N
        jLabelErrorLastName.setForeground(new java.awt.Color(205, 92, 92));
        jPanelForm.add(jLabelErrorLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 47, 200, 14));

        jPanelButtonCreate.setBackground(new java.awt.Color(156, 39, 176));

        jLabelButtonCreate.setFont(new java.awt.Font("Hind Siliguri Medium", 0, 14)); // NOI18N
        jLabelButtonCreate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelButtonCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonCreate.setText("Crear autor");
        jLabelButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonCreateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonCreateLayout = new javax.swing.GroupLayout(jPanelButtonCreate);
        jPanelButtonCreate.setLayout(jPanelButtonCreateLayout);
        jPanelButtonCreateLayout.setHorizontalGroup(
            jPanelButtonCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButtonCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );
        jPanelButtonCreateLayout.setVerticalGroup(
            jPanelButtonCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButtonCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanelForm.add(jPanelButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 111, 97, 32));

        jPanelContent.add(jPanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 86, 420, 143));

        getContentPane().add(jPanelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 475, 246));

        bg.setPreferredSize(new java.awt.Dimension(505, 406));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/bg_new_author.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(505, 406));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(505, 406));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 505, 276));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Eventos que permiten arrastrar la ventana desde la barra superior
     */
    private void jPanelTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelTopMousePressed

    private void jPanelTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelTopMouseDragged

    /**
     * Eventos que perminen a los botones cerrar y minimizar ventana
     */
    private void jImgCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImgCloseMouseEntered
        jPanelClose.setBackground(new java.awt.Color(245, 245, 245));
    }//GEN-LAST:event_jImgCloseMouseEntered

    private void jImgCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImgCloseMouseExited
        jPanelClose.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jImgCloseMouseExited

    private void jImgCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImgCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jImgCloseMouseClicked

    /**
     * Eventos de TextFied para simular el focos en un JPanel
     */
    private void jTextFieldNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameFocusGained
        chanceColorFocusSeparator("Gained", jPanelFocusName);
    }//GEN-LAST:event_jTextFieldNameFocusGained

    private void jTextFieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameFocusLost
        chanceColorFocusSeparator("Lost", jPanelFocusName);
    }//GEN-LAST:event_jTextFieldNameFocusLost

    private void jTextFieldLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLastNameFocusGained
        chanceColorFocusSeparator("Gained", jPanelFocusLastName);
    }//GEN-LAST:event_jTextFieldLastNameFocusGained

    private void jTextFieldLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLastNameFocusLost
        chanceColorFocusSeparator("Lost", jPanelFocusLastName);
    }//GEN-LAST:event_jTextFieldLastNameFocusLost

    /**
     * Metodo que permite cambiar de color de JPanel que esta debajo de un
     * TextFied para mejorar la experiencia de usurio. Dependiendo del tipo que
     * ingrese "Gained" : color de foco, o "Lost": color normal Ingresa el
     * JPanel al que se aplica el cambio
     *
     * @param tipo
     * @param panelSeparator
     */
    public void chanceColorFocusSeparator(String tipo, JPanel panelSeparator) {
        if (tipo.equals("Gained")) {
            panelSeparator.setBackground(new java.awt.Color(123, 31, 162));
            return;
        }
        if (tipo.equals("Lost")) {
            panelSeparator.setBackground(new java.awt.Color(158, 158, 158));
        }
    }

    /**
     * Eventos de boton "Crear autor". Mejorar apariencial al entrar con el
     * mouse
     */
    private void jLabelButtonCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCreateMouseEntered
        jPanelButtonCreate.setBackground(new java.awt.Color(123, 31, 162));
    }//GEN-LAST:event_jLabelButtonCreateMouseEntered

    private void jLabelButtonCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCreateMouseExited
        jPanelButtonCreate.setBackground(new java.awt.Color(156, 39, 176));
    }//GEN-LAST:event_jLabelButtonCreateMouseExited

    /**
     * Evento click del boton "Crear autor".
     */
    private void jLabelButtonCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCreateMouseClicked
        /* Limpiar todos los mensajes de error dentro del formulario */
        cleanjLabelsError();
        /* Validar que todos los campos esten con el formato correcto */
        if (!validarCamposFormato()) {
            return;
        }
        
        Author author = new Author();
        author.setName(jTextFieldName.getText()+ " "+ jTextFieldLastName.getText());

        /* Enviar datos del nuevo autor a la base de datos */
        try {
            // Se comprueba que los datos se ingresen correctamente a la base
            if (AuthorController.createAuthor(author) > 0) {
                openDialogAlert("successful", " ","Creado correctamente","");
                // Limpiar campos
                cleanjLabelsError();
                cleanjTextFields();
                jTextFieldName.requestFocus();
            // Sino lanzar un mensaje de alerta    
            } else {
                openDialogAlert("warning", "Error al crear","");
            }
        } catch (Exception e) {
            // Errores con la base de datos
            if (e.getLocalizedMessage().equals("3011")) {
                openDialogAlert("danger", "No se puede establecer conexión con el","servidor");
            } else {
                openDialogAlert("danger", "Error al momento de consultar al servidor","");
            }
        }

    }//GEN-LAST:event_jLabelButtonCreateMouseClicked

    /* Métodos que crean un alert para lanzar un mensaje*/
    private void openDialogAlert(String tipo, String message1, String message2) {
        DialogAlert dialogAlert = new DialogAlert(jFrameParent, true, tipo, message1, message2);
        dialogAlert.setVisible(true);
    }
    
    private void openDialogAlert(String tipo,String title, String message1, String message2) {
        DialogAlert dialogAlert = new DialogAlert(jFrameParent, true, tipo,title, message1, message2);
        dialogAlert.setVisible(true);
    }

    /**
     * Método que permite validar los datos que el usuario ingresa antes de
     * enviar hacia la base de datos. Este retornara un boolean para verificar
     * que todos los campos esten correctamente ingresados.
     *
     * @return
     */
    private boolean validarCamposFormato() {
        //variable de verificación de los campos
        boolean verif = true;
        /* Validación del nombre: no debe quedar vacio */
        if (jTextFieldName.getText().length() < 1) {
            verif = false;
            jLabelErrorName.setText("Olvidaste ingresar el nombre.");
        }
        /* Validación del apellido: no debe quedar vacio */
        if (jTextFieldLastName.getText().length() < 1) {
            verif = false;
            jLabelErrorLastName.setText("Olvidaste ingrese el apellido.");
        }
        
        return verif;
    }

    /**
     * Metodo que permite limpiar mensaje de error de los jLabels
     */
    private void cleanjLabelsError() {
        jLabelErrorName.setText("");
        jLabelErrorLastName.setText("");
    }

    /**
     * Metodo que permite limpiar todos los campos de TextField
     */
    private void cleanjTextFields() {
        jTextFieldName.setText("");
        jTextFieldLastName.setText("");
    }

    /**
     * Metodo que valida si un correo electronico tiene el formaro correcto
     *
     * @param email
     * @return
     */
    public static boolean ValidarMail(String email) {
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(email);
        return mather.find();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jImgClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelButtonCreate;
    private javax.swing.JLabel jLabelErrorLastName;
    private javax.swing.JLabel jLabelErrorName;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelButtonCreate;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelDivide;
    private javax.swing.JPanel jPanelFocusLastName;
    private javax.swing.JPanel jPanelFocusName;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables

}
