package com.galosanchez.view;

import java.awt.Color;

/**
 * Esta clase permite crear un Alert, asignando un mensaje e ícono
 * @author Galo Sánchez
 */
public class DialogAlert extends javax.swing.JDialog {

    private int xMouse, yMouse;
    
    public DialogAlert(java.awt.Frame parent, boolean modal, String tipo, String message1, String message2) {
        super(parent, modal);
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        bg.setBackground(new Color(0, 0, 0, 0));
        setIcon(tipo);
        setTitle(message1, message2);
    }
    
    public DialogAlert(java.awt.Frame parent, boolean modal, String tipo, String title,String message1, String message2) {
        super(parent, modal);
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        bg.setBackground(new Color(0, 0, 0, 0));
        setIcon(tipo);
        setTitle(message1, message2);
        if(!title.equals("")){
            jLabelTitle.setText(title);
        }
    }
    
    /**
     * Método que asigna el mensaje en el alert
     * @param message1
     * @param message2 
     */
    private void setTitle(String message1, String message2){
        jLabelMessage1.setText(message1);
        jLabelMessage2.setText(message2);
    }
    
    /**
     * Método que asigna el ícono al alert
     * @param tipo 
     */
    private void setIcon(String tipo){
        String image;
        switch(tipo){
            case "danger":
                image = "img_danger_60.png";
                break;
            case "warning":
                image = "img_warning_60.png";
                break;
            case "successful":
                image = "img_successful_60.png";
                break;
            default:
                image = null;
        }
        if(image != null){
            jLabelImgOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/"+image)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainer = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelImgOption = new javax.swing.JLabel();
        jPanelClose = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelMessage1 = new javax.swing.JLabel();
        jLabelMessage2 = new javax.swing.JLabel();
        jPanelButton = new javax.swing.JPanel();
        jLabelButton = new javax.swing.JLabel();
        jPanelMove = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelContainer.setBackground(new java.awt.Color(245, 245, 245));
        jPanelContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTop.setBackground(new java.awt.Color(123, 31, 162));
        jPanelTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImgOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelTop.add(jLabelImgOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 0, 232, 80));

        jPanelClose.setBackground(new java.awt.Color(123, 31, 162));

        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/img_close_alert.png"))); // NOI18N
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCloseLayout = new javax.swing.GroupLayout(jPanelClose);
        jPanelClose.setLayout(jPanelCloseLayout);
        jPanelCloseLayout.setHorizontalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelClose, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );
        jPanelCloseLayout.setVerticalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelClose, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanelTop.add(jPanelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 0, 34, 34));

        jPanelContainer.add(jPanelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 80));

        jLabelTitle.setFont(new java.awt.Font("Hind Siliguri SemiBold", 0, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Ooops!");
        jPanelContainer.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 300, 25));

        jLabelMessage1.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelMessage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelContainer.add(jLabelMessage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 280, 20));

        jLabelMessage2.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelMessage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelContainer.add(jLabelMessage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, 280, 20));

        jPanelButton.setBackground(new java.awt.Color(156, 39, 176));

        jLabelButton.setFont(new java.awt.Font("Hind Siliguri Medium", 0, 14)); // NOI18N
        jLabelButton.setForeground(new java.awt.Color(255, 255, 255));
        jLabelButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButton.setText("Aceptar");
        jLabelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonLayout = new javax.swing.GroupLayout(jPanelButton);
        jPanelButton.setLayout(jPanelButtonLayout);
        jPanelButtonLayout.setHorizontalGroup(
            jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );
        jPanelButtonLayout.setVerticalGroup(
            jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanelContainer.add(jPanelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 171, 78, 32));

        jPanelMove.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelMoveMouseDragged(evt);
            }
        });
        jPanelMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelMoveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMoveLayout = new javax.swing.GroupLayout(jPanelMove);
        jPanelMove.setLayout(jPanelMoveLayout);
        jPanelMoveLayout.setHorizontalGroup(
            jPanelMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanelMoveLayout.setVerticalGroup(
            jPanelMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelContainer.add(jPanelMove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 30));

        getContentPane().add(jPanelContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 300, 213));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/bg_dialog_alert.png"))); // NOI18N

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 233));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Eventos que permiten arrastrar la ventana desde la barra superior
     */
    private void jPanelMoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMoveMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelMoveMousePressed

    private void jPanelMoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMoveMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelMoveMouseDragged

    /**
     * Eventos que perminen a los botones cerrar y minimizar ventana
     */
    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        jPanelClose.setBackground(new java.awt.Color(136, 53, 171));
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        jPanelClose.setBackground(new java.awt.Color(123, 31, 162));
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMouseEntered
        jPanelButton.setBackground(new java.awt.Color(123, 31, 162));
    }//GEN-LAST:event_jLabelButtonMouseEntered

    private void jLabelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMouseExited
        jPanelButton.setBackground(new java.awt.Color(156,39,176));
    }//GEN-LAST:event_jLabelButtonMouseExited

    /* Al hacer clic en aceptar el alert se cierra */
    private void jLabelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelButton;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelImgOption;
    private javax.swing.JLabel jLabelMessage1;
    private javax.swing.JLabel jLabelMessage2;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelMove;
    private javax.swing.JPanel jPanelTop;
    // End of variables declaration//GEN-END:variables
}
