package com.galosanchez.view;

import com.galosanchez.domain.User;
import javax.swing.JFrame;

/**
 * Esta clase crea el panel de administración de cuenta
 * @author Galo Sánchez
 */
public class JPanelCount extends javax.swing.JPanel {

    private final JFrame jFrameParent;
    private final User user;

    public JPanelCount(JFrame jFrameParent, User user) {
        this.user = user;
        this.jFrameParent = jFrameParent;
        initComponents();
        loadData();
    }

    /**
     * Carga los datos del estudiante a los componentes
     */
    private void loadData(){
        jTextFieldUser.setText(user.getUser());
        jTextFieldName.setText(user.getName());
        jTextFieldEmail.setText(user.getEmail());
        jTextFieldCreateAt.setText(user.getCreatedAt().toString());
        if(user.getType() == 'A'){
            jTextFieldType.setText("Administrador");
        }else{
            jTextFieldType.setText("Normal");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAddStudent = new javax.swing.JPanel();
        jLabelLogOut = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabelName1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelName2 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelName3 = new javax.swing.JLabel();
        jTextFieldCreateAt = new javax.swing.JTextField();
        jLabelName4 = new javax.swing.JLabel();
        jTextFieldType = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(919, 586));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(874, 568));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Hind Siliguri Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 33, 33));
        jLabel1.setText("Información de la cuenta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 24));

        jPanelAddStudent.setBackground(new java.awt.Color(156, 39, 176));

        jLabelLogOut.setFont(new java.awt.Font("Hind Siliguri Medium", 0, 14)); // NOI18N
        jLabelLogOut.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogOut.setText("Cerrar sesión");
        jLabelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddStudentLayout = new javax.swing.GroupLayout(jPanelAddStudent);
        jPanelAddStudent.setLayout(jPanelAddStudentLayout);
        jPanelAddStudentLayout.setHorizontalGroup(
            jPanelAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );
        jPanelAddStudentLayout.setVerticalGroup(
            jPanelAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 538, 108, 32));

        jLabelName.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(158, 158, 158));
        jLabelName.setText("Usuario");
        jPanel1.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, -1, 16));

        jTextFieldUser.setEditable(false);
        jTextFieldUser.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldUser.setFont(new java.awt.Font("Hind Siliguri", 0, 16)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(33, 33, 33));
        jTextFieldUser.setBorder(null);
        jPanel1.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 200, 20));

        jLabelName1.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelName1.setForeground(new java.awt.Color(158, 158, 158));
        jLabelName1.setText("Nombre");
        jPanel1.add(jLabelName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 54, -1, 16));

        jTextFieldName.setEditable(false);
        jTextFieldName.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldName.setFont(new java.awt.Font("Hind Siliguri", 0, 16)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(33, 33, 33));
        jTextFieldName.setBorder(null);
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 76, 200, 20));

        jLabelName2.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelName2.setForeground(new java.awt.Color(158, 158, 158));
        jLabelName2.setText("Email");
        jPanel1.add(jLabelName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, -1, 16));

        jTextFieldEmail.setEditable(false);
        jTextFieldEmail.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldEmail.setFont(new java.awt.Font("Hind Siliguri", 0, 16)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(33, 33, 33));
        jTextFieldEmail.setBorder(null);
        jPanel1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 132, 420, 20));

        jLabelName3.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelName3.setForeground(new java.awt.Color(158, 158, 158));
        jLabelName3.setText("Creación de la cuenta");
        jPanel1.add(jLabelName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 168, -1, 16));

        jTextFieldCreateAt.setEditable(false);
        jTextFieldCreateAt.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldCreateAt.setFont(new java.awt.Font("Hind Siliguri", 0, 16)); // NOI18N
        jTextFieldCreateAt.setForeground(new java.awt.Color(33, 33, 33));
        jTextFieldCreateAt.setBorder(null);
        jPanel1.add(jTextFieldCreateAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 188, 200, 20));

        jLabelName4.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelName4.setForeground(new java.awt.Color(158, 158, 158));
        jLabelName4.setText("Tipo de usuario");
        jPanel1.add(jLabelName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 168, -1, 16));

        jTextFieldType.setEditable(false);
        jTextFieldType.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldType.setFont(new java.awt.Font("Hind Siliguri", 0, 16)); // NOI18N
        jTextFieldType.setForeground(new java.awt.Color(33, 33, 33));
        jTextFieldType.setBorder(null);
        jPanel1.add(jTextFieldType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 188, 200, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 440, 570));

        jPanel2.setBackground(new java.awt.Color(233, 224, 237));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/ic_school_large.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 16, 440, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseEntered
        jPanelAddStudent.setBackground(new java.awt.Color(123, 31, 162));
    }//GEN-LAST:event_jLabelLogOutMouseEntered

    private void jLabelLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseExited
        jPanelAddStudent.setBackground(new java.awt.Color(156, 39, 176));
    }//GEN-LAST:event_jLabelLogOutMouseExited

    private void jLabelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseClicked
        jFrameParent.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jLabelLogOutMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelName1;
    private javax.swing.JLabel jLabelName2;
    private javax.swing.JLabel jLabelName3;
    private javax.swing.JLabel jLabelName4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAddStudent;
    private javax.swing.JTextField jTextFieldCreateAt;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldType;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables

}
