package com.galosanchez.view;

import com.galosanchez.controller.UserController;
import javax.swing.JFrame;

/**
 * Esta clase crea el panel de Home
 * @author Galo Sánchez
 */
public class JPanelHome extends javax.swing.JPanel {

    private final JFrame jFrameParent;
    
    public JPanelHome(JFrame jFrameParent) {
        this.jFrameParent = jFrameParent;
        initComponents();
        uploadData(getData());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bgImage = new javax.swing.JPanel();
        jLabelImageHome = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jPanelStudents = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelNumberStudent = new javax.swing.JLabel();
        jLabelIcStudents = new javax.swing.JLabel();
        jLabelTitleCardStudents = new javax.swing.JLabel();
        jPanelBooks = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabelNumberBooks = new javax.swing.JLabel();
        jLabelIcBooks = new javax.swing.JLabel();
        jLabelTitleCardBook = new javax.swing.JLabel();
        jPanelLending = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabelNumberLending = new javax.swing.JLabel();
        jLabelIcLending = new javax.swing.JLabel();
        jLabelTitleCardLending = new javax.swing.JLabel();
        jPanelLendingPending = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabelNumberPending = new javax.swing.JLabel();
        jLabelIcLendingPending = new javax.swing.JLabel();
        jLabelTitleCardLendingPending = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setMinimumSize(new java.awt.Dimension(914, 578));
        setPreferredSize(new java.awt.Dimension(914, 578));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(245, 245, 245));
        bg.setMinimumSize(new java.awt.Dimension(0, 0));
        bg.setPreferredSize(new java.awt.Dimension(874, 568));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgImage.setBackground(new java.awt.Color(233, 224, 237));
        bgImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImageHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/img_library_home.jpg"))); // NOI18N
        bgImage.add(jLabelImageHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 422));

        jLabelTitle.setFont(new java.awt.Font("Hind Siliguri SemiBold", 0, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(33, 33, 33));
        jLabelTitle.setText("Biblioteca escolar");
        bgImage.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 28, -1, 30));

        jLabelDescription.setFont(new java.awt.Font("Hind Siliguri", 0, 14)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(97, 97, 97));
        jLabelDescription.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDescription.setText("<html>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</html>");
        jLabelDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bgImage.add(jLabelDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 62, 280, 340));

        bg.add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 879, 422));

        jPanelStudents.setBackground(new java.awt.Color(158, 158, 158));
        jPanelStudents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNumberStudent.setFont(new java.awt.Font("Hind Siliguri SemiBold", 0, 18)); // NOI18N
        jLabelNumberStudent.setForeground(new java.awt.Color(158, 158, 158));
        jLabelNumberStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumberStudent.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNumberStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNumberStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelStudents.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 87, 188, 40));

        jLabelIcStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIcStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/ic_users_40.png"))); // NOI18N
        jPanelStudents.add(jLabelIcStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 190, 40));

        jLabelTitleCardStudents.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitleCardStudents.setFont(new java.awt.Font("Hind Siliguri SemiBold", 0, 16)); // NOI18N
        jLabelTitleCardStudents.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleCardStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleCardStudents.setText("Estudiantes");
        jPanelStudents.add(jLabelTitleCardStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 25));

        bg.add(jPanelStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 442, 190, 128));

        jPanelBooks.setBackground(new java.awt.Color(158, 158, 158));
        jPanelBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNumberBooks.setFont(new java.awt.Font("Hind Siliguri SemiBold", 0, 18)); // NOI18N
        jLabelNumberBooks.setForeground(new java.awt.Color(158, 158, 158));
        jLabelNumberBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumberBooks.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNumberBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNumberBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelBooks.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 87, 188, 40));

        jLabelIcBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIcBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/ic_book_40.png"))); // NOI18N
        jPanelBooks.add(jLabelIcBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 190, 40));

        jLabelTitleCardBook.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitleCardBook.setFont(new java.awt.Font("Hind Siliguri SemiBold", 0, 16)); // NOI18N
        jLabelTitleCardBook.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleCardBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleCardBook.setText("Libros");
        jPanelBooks.add(jLabelTitleCardBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 25));

        bg.add(jPanelBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 442, 190, 128));

        jPanelLending.setBackground(new java.awt.Color(158, 158, 158));
        jPanelLending.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNumberLending.setFont(new java.awt.Font("Hind Siliguri SemiBold", 0, 18)); // NOI18N
        jLabelNumberLending.setForeground(new java.awt.Color(158, 158, 158));
        jLabelNumberLending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumberLending.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNumberLending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNumberLending, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelLending.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 87, 188, 40));

        jLabelIcLending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIcLending.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/ic_lending_40.png"))); // NOI18N
        jPanelLending.add(jLabelIcLending, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 190, 40));

        jLabelTitleCardLending.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitleCardLending.setFont(new java.awt.Font("Hind Siliguri SemiBold", 0, 16)); // NOI18N
        jLabelTitleCardLending.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleCardLending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleCardLending.setText("Prestamos");
        jPanelLending.add(jLabelTitleCardLending, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 25));

        bg.add(jPanelLending, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 442, 190, 128));

        jPanelLendingPending.setBackground(new java.awt.Color(158, 158, 158));
        jPanelLendingPending.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNumberPending.setFont(new java.awt.Font("Hind Siliguri SemiBold", 0, 18)); // NOI18N
        jLabelNumberPending.setForeground(new java.awt.Color(158, 158, 158));
        jLabelNumberPending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumberPending.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNumberPending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNumberPending, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelLendingPending.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 87, 188, 40));

        jLabelIcLendingPending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIcLendingPending.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/ic_lending_pending_40.png"))); // NOI18N
        jPanelLendingPending.add(jLabelIcLendingPending, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 190, 40));

        jLabelTitleCardLendingPending.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitleCardLendingPending.setFont(new java.awt.Font("Hind Siliguri SemiBold", 0, 16)); // NOI18N
        jLabelTitleCardLendingPending.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleCardLendingPending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleCardLendingPending.setText("Devoluciones pendientes");
        jPanelLendingPending.add(jLabelTitleCardLendingPending, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 25));

        bg.add(jPanelLendingPending, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 442, 190, 128));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 879, 570));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgImage;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelIcBooks;
    private javax.swing.JLabel jLabelIcLending;
    private javax.swing.JLabel jLabelIcLendingPending;
    private javax.swing.JLabel jLabelIcStudents;
    private javax.swing.JLabel jLabelImageHome;
    private javax.swing.JLabel jLabelNumberBooks;
    private javax.swing.JLabel jLabelNumberLending;
    private javax.swing.JLabel jLabelNumberPending;
    private javax.swing.JLabel jLabelNumberStudent;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitleCardBook;
    private javax.swing.JLabel jLabelTitleCardLending;
    private javax.swing.JLabel jLabelTitleCardLendingPending;
    private javax.swing.JLabel jLabelTitleCardStudents;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelBooks;
    private javax.swing.JPanel jPanelLending;
    private javax.swing.JPanel jPanelLendingPending;
    private javax.swing.JPanel jPanelStudents;
    // End of variables declaration//GEN-END:variables

    private int[] getData() {
        int[] arrayData = new int[4];
        try {
            arrayData = UserController.listDataHome();
            return arrayData;
        } catch (Exception e) {
            if (e.getLocalizedMessage().equals("3011")) {
                openDialogAlert("danger", "No se puede establecer conexión con el", "servidor");
            } else {
                openDialogAlert("danger", "Error al momento de consultar al servidor", "");
            }
        }
        return null;
    }
    
    private void openDialogAlert(String tipo, String message1, String message2) {
        DialogAlert dialogAlert = new DialogAlert(jFrameParent, true, tipo, message1, message2);
        dialogAlert.setVisible(true);
    }

    private void uploadData(int[] data) {
        jLabelNumberStudent.setText(String.valueOf(data[0]));
        jLabelNumberBooks.setText(String.valueOf(data[1]));
        jLabelNumberLending.setText(String.valueOf(data[2]));
        jLabelNumberPending.setText(String.valueOf(data[3]));
        
    }

}
