package com.galosanchez.view;

import com.galosanchez.controller.UserController;
import com.galosanchez.domain.User;
import javax.swing.ImageIcon;

/**
 * Esta clase crea el panel de Login
 * @author Galo Sánchez
 */
public class Login extends javax.swing.JFrame {

    private int xMouse, yMouse;

    public Login() {

        initComponents();
        
        jLabelButton.setFocusable(true);
        jLabelButton.requestFocus();
        
        /* Asignar ícino de barra de tareas*/
        setIconImage(new ImageIcon(getClass().getResource("/com/galosanchez/images/icon_main.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabelPortada = new javax.swing.JLabel();
        jPanelTop = new javax.swing.JPanel();
        jPanelClose = new javax.swing.JPanel();
        jLabelImageClose = new javax.swing.JLabel();
        jPanelMinimize = new javax.swing.JPanel();
        jLabelImageMinize = new javax.swing.JLabel();
        jPanelContainer = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelTitleUser = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPanelSeparator1 = new javax.swing.JPanel();
        jLabelErrorUser = new javax.swing.JLabel();
        jLabelTitlePassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jPanelSeparator2 = new javax.swing.JPanel();
        jLabelErrorPassword = new javax.swing.JLabel();
        jPanelButtonLogin = new javax.swing.JPanel();
        jLabelButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca escolar");
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(245, 245, 245));
        bg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(158, 158, 158), 1, true));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/img_portada_library.jpg"))); // NOI18N
        bg.add(jLabelPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelTop.setBackground(new java.awt.Color(245, 245, 245));
        jPanelTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelTopMouseDragged(evt);
            }
        });
        jPanelTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTopMousePressed(evt);
            }
        });
        jPanelTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelClose.setBackground(new java.awt.Color(245, 245, 245));
        jPanelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCloseMouseExited(evt);
            }
        });

        jLabelImageClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/img_close_normal.png"))); // NOI18N

        javax.swing.GroupLayout jPanelCloseLayout = new javax.swing.GroupLayout(jPanelClose);
        jPanelClose.setLayout(jPanelCloseLayout);
        jPanelCloseLayout.setHorizontalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImageClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCloseLayout.setVerticalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImageClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelTop.add(jPanelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 0, 34, 24));

        jPanelMinimize.setBackground(new java.awt.Color(245, 245, 245));
        jPanelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMinimizeMouseExited(evt);
            }
        });

        jLabelImageMinize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/img_minimize_normal.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMinimizeLayout = new javax.swing.GroupLayout(jPanelMinimize);
        jPanelMinimize.setLayout(jPanelMinimizeLayout);
        jPanelMinimizeLayout.setHorizontalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImageMinize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMinimizeLayout.setVerticalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImageMinize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelTop.add(jPanelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 34, 24));

        bg.add(jPanelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 698, 24));

        jPanelContainer.setBackground(new java.awt.Color(245, 245, 245));
        jPanelContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setFont(new java.awt.Font("Hind Siliguri", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(33, 33, 33));
        jLabelTitle.setText("Iniciar sesión");
        jPanelContainer.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabelTitleUser.setFont(new java.awt.Font("Hind Siliguri Medium", 0, 14)); // NOI18N
        jLabelTitleUser.setForeground(new java.awt.Color(42, 42, 42));
        jLabelTitleUser.setText("Usuario");
        jPanelContainer.add(jLabelTitleUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 16));

        jTextFieldUser.setBackground(new java.awt.Color(245, 245, 245));
        jTextFieldUser.setFont(new java.awt.Font("Hind Siliguri", 0, 16)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(158, 158, 158));
        jTextFieldUser.setText("Ingrese nombre de usuario");
        jTextFieldUser.setToolTipText("");
        jTextFieldUser.setBorder(null);
        jTextFieldUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUserFocusGained(evt);
            }
        });
        jPanelContainer.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 300, 20));

        jPanelSeparator1.setBackground(new java.awt.Color(158, 158, 158));

        javax.swing.GroupLayout jPanelSeparator1Layout = new javax.swing.GroupLayout(jPanelSeparator1);
        jPanelSeparator1.setLayout(jPanelSeparator1Layout);
        jPanelSeparator1Layout.setHorizontalGroup(
            jPanelSeparator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanelSeparator1Layout.setVerticalGroup(
            jPanelSeparator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanelContainer.add(jPanelSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, -1, 1));

        jLabelErrorUser.setFont(new java.awt.Font("Hind Siliguri", 0, 12)); // NOI18N
        jLabelErrorUser.setForeground(new java.awt.Color(205, 92, 92));
        jPanelContainer.add(jLabelErrorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 107, 300, 14));

        jLabelTitlePassword.setFont(new java.awt.Font("Hind Siliguri Medium", 0, 14)); // NOI18N
        jLabelTitlePassword.setForeground(new java.awt.Color(42, 42, 42));
        jLabelTitlePassword.setText("Contraseña");
        jPanelContainer.add(jLabelTitlePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 300, 16));

        jPasswordField.setBackground(new java.awt.Color(245, 245, 245));
        jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(158, 158, 158));
        jPasswordField.setText("**********");
        jPasswordField.setBorder(null);
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
        });
        jPanelContainer.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 151, 300, 20));

        jPanelSeparator2.setBackground(new java.awt.Color(158, 158, 158));

        javax.swing.GroupLayout jPanelSeparator2Layout = new javax.swing.GroupLayout(jPanelSeparator2);
        jPanelSeparator2.setLayout(jPanelSeparator2Layout);
        jPanelSeparator2Layout.setHorizontalGroup(
            jPanelSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanelSeparator2Layout.setVerticalGroup(
            jPanelSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanelContainer.add(jPanelSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, -1, 1));

        jLabelErrorPassword.setFont(new java.awt.Font("Hind Siliguri", 0, 12)); // NOI18N
        jLabelErrorPassword.setForeground(new java.awt.Color(205, 92, 92));
        jPanelContainer.add(jLabelErrorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 177, 300, 14));

        jPanelButtonLogin.setBackground(new java.awt.Color(156, 39, 176));

        jLabelButton.setBackground(new java.awt.Color(0, 0, 0));
        jLabelButton.setFont(new java.awt.Font("Hind Siliguri Medium", 0, 14)); // NOI18N
        jLabelButton.setForeground(new java.awt.Color(255, 255, 255));
        jLabelButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButton.setText("Iniciar sesión");
        jLabelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonLoginLayout = new javax.swing.GroupLayout(jPanelButtonLogin);
        jPanelButtonLogin.setLayout(jPanelButtonLoginLayout);
        jPanelButtonLoginLayout.setHorizontalGroup(
            jPanelButtonLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanelButtonLoginLayout.setVerticalGroup(
            jPanelButtonLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelContainer.add(jPanelButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 274, 120, 32));

        bg.add(jPanelContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 54, 300, 306));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /* Eventos de barra superior */
    private void jPanelTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelTopMousePressed

    private void jPanelTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelTopMouseDragged

    private void jPanelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCloseMouseEntered
        jLabelImageClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/img_close_click.png")));
        jPanelClose.setBackground(new java.awt.Color(205, 92, 92));
    }//GEN-LAST:event_jPanelCloseMouseEntered

    private void jPanelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCloseMouseExited
        jLabelImageClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/img_close_normal.png")));
        jPanelClose.setBackground(new java.awt.Color(245, 245, 245));
    }//GEN-LAST:event_jPanelCloseMouseExited

    private void jPanelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizeMouseEntered
        jLabelImageMinize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/img_minimize_click.png")));
        jPanelMinimize.setBackground(new java.awt.Color(158, 158, 158));
    }//GEN-LAST:event_jPanelMinimizeMouseEntered

    private void jPanelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizeMouseExited
        jLabelImageMinize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galosanchez/images/img_minimize_normal.png")));
        jPanelMinimize.setBackground(new java.awt.Color(245, 245, 245));
    }//GEN-LAST:event_jPanelMinimizeMouseExited

    private void jPanelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanelCloseMouseClicked

    private void jPanelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizeMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jPanelMinimizeMouseClicked

    private void jTextFieldUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUserFocusGained
        jPanelSeparator1.setBackground(new java.awt.Color(123,31,162));
        jPanelSeparator2.setBackground(new java.awt.Color(158,158,158));
        if (jTextFieldUser.getText().equals("Ingrese nombre de usuario")) {
            jTextFieldUser.setText("");
            jTextFieldUser.setForeground(new java.awt.Color(33, 33, 33));
        }
        if (String.valueOf(jPasswordField.getPassword()).length() < 1) {
            jPasswordField.setText("**********");
            jPasswordField.setForeground(new java.awt.Color(158,158,158));
        }
    }//GEN-LAST:event_jTextFieldUserFocusGained

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
        jPanelSeparator2.setBackground(new java.awt.Color(123,31,162));
        jPanelSeparator1.setBackground(new java.awt.Color(158,158,158));
        if (String.valueOf(jPasswordField.getPassword()).equals("**********")) {
            jPasswordField.setText("");
            jPasswordField.setForeground(new java.awt.Color(33, 33, 33));
        }
        if (jTextFieldUser.getText().length() < 1) {
            jTextFieldUser.setText("Ingrese nombre de usuario");
            jTextFieldUser.setForeground(new java.awt.Color(158,158,158));
        }
    }//GEN-LAST:event_jPasswordFieldFocusGained

    private void jLabelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMouseExited
        jPanelButtonLogin.setBackground(new java.awt.Color(156,39,176));
    }//GEN-LAST:event_jLabelButtonMouseExited

    /**
     * Login
     */
    private void jLabelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMouseClicked

        String userString, passwordString;
        User user;
        boolean valid = true;
        userString = jTextFieldUser.getText();
        passwordString = String.valueOf(jPasswordField.getPassword());

        // Validar datos
        jLabelErrorUser.setText("");
        jLabelErrorPassword.setText("");

        if (userString.equals("Ingrese nombre de usuario") || userString.length() < 1) {
            jLabelErrorUser.setText("Ingrese su usuario");
            valid = false;
        }
        if (passwordString.equals("**********") || passwordString.length() < 1) {
            jLabelErrorPassword.setText("Ingrese su contraseña");
            valid = false;
        }

        if (valid) {
            user = new User(userString, passwordString);
            try {
                // Consulta a la base de datos
                user = UserController.login(user);
                if ( user != null ) {
                    this.dispose();
                    Home frmHome = new Home(user);
                    frmHome.setVisible(true);
                    
                } else {
                    openDialogAlert("warning", "El usuario o la contraseña son incorrectas.","");

                }
            } catch (Exception e) {
                if( e.getLocalizedMessage().equals("3011")){
                    openDialogAlert("danger", "No se puede establecer conexión con el","servidor");
                }else{
                    openDialogAlert("danger", "Error al momento de consultar al servidor","");
                }
                

            }

        }
    }//GEN-LAST:event_jLabelButtonMouseClicked

    private void jLabelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonMouseEntered
        jPanelButtonLogin.setBackground(new java.awt.Color(123, 31, 162));
    }//GEN-LAST:event_jLabelButtonMouseEntered

    private void openDialogAlert(String tipo, String message1, String message2) {
        DialogAlert dialogAlert = new DialogAlert(this, true, tipo, message1, message2);
        dialogAlert.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabelButton;
    private javax.swing.JLabel jLabelErrorPassword;
    private javax.swing.JLabel jLabelErrorUser;
    private javax.swing.JLabel jLabelImageClose;
    private javax.swing.JLabel jLabelImageMinize;
    private javax.swing.JLabel jLabelPortada;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitlePassword;
    private javax.swing.JLabel jLabelTitleUser;
    private javax.swing.JPanel jPanelButtonLogin;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelMinimize;
    private javax.swing.JPanel jPanelSeparator1;
    private javax.swing.JPanel jPanelSeparator2;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
